<?xml version="1.0" encoding="UTF-8"?>
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" xmlns:vars="http://technodrom.scravy.de/2010/data" xmlns:item="http://technodrom.scravy.de/2010/item">

<xsl:import href="global.xsl" />

<xsl:template mode="title" match="vars:meta">
	<xsl:text>Noten &amp; Bescheinigungen</xsl:text>
</xsl:template>

<xsl:template mode="content" match="vars:meta">
	<h1>Meine Noten &amp; Bescheinigungen</h1>
	
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero risus, mollis a convallis sed, malesuada ac libero. Aliquam accumsan rhoncus enim, vel interdum velit laoreet vel. Aliquam consectetur ipsum nec orci sagittis ac lacinia risus suscipit. Sed accumsan pellentesque lacus, auctor pretium ligula semper ac. Phasellus cursus neque ut risus accumsan consequat. Aenean eu nulla adipiscing leo laoreet faucibus. Curabitur molestie lorem in mauris dignissim iaculis in ullamcorper nisl. Curabitur bibendum est auctor mauris suscipit semper. Quisque a odio id nibh consequat eleifend. Integer id volutpat purus. Morbi tempor dignissim metus vel vulputate. Fusce placerat, lorem convallis sagittis pretium, libero arcu laoreet elit, vitae mattis turpis lacus nec arcu. Quisque quis odio eu risus adipiscing semper nec sit amet erat. Nulla eu orci quis ante sollicitudin egestas sed sed metus. Duis luctus tellus nunc, in vulputate ligula. Donec mollis enim quis leo pellentesque a porttitor augue vestibulum. Fusce elit lectus, laoreet eu imperdiet sit amet, iaculis sed felis.
</p><p>Donec porttitor condimentum mattis. Sed augue lorem, varius eu pulvinar mattis, porta vel nunc. Quisque dictum imperdiet orci, a porta libero hendrerit a. In metus est, ultrices id pellentesque et, fringilla ut magna. Donec urna lacus, scelerisque non mollis et, dapibus sed erat. Fusce dolor sapien, commodo laoreet malesuada eget, faucibus vitae purus. Proin posuere est vitae arcu fringilla scelerisque. In convallis porta erat, sed tristique purus varius id. Nam auctor magna a justo pharetra fermentum. Praesent dignissim eleifend sem, pulvinar commodo turpis aliquet et. Curabitur non nibh id felis pellentesque luctus eu in purus. Mauris fermentum orci blandit lorem dictum scelerisque. Nunc sed orci metus, pellentesque viverra risus. Ut et varius elit. Maecenas posuere ultrices neque, id tincidunt ante interdum at. Nulla viverra molestie mi, a eleifend arcu varius eu.
</p><p>Suspendisse dolor neque, porttitor at viverra sed, pulvinar nec est. Nulla et sollicitudin eros. Vestibulum scelerisque erat non nibh consequat in aliquam velit faucibus. Vestibulum quis sagittis sem. Nunc a blandit purus. Suspendisse tortor dolor, convallis id volutpat interdum, interdum at sem. Pellentesque ultrices erat dignissim arcu ornare sagittis. Donec orci felis, imperdiet id eleifend nec, mattis vitae urna. Morbi et massa est, at venenatis mi. Praesent mattis ultrices massa eu ultrices. Maecenas ornare massa sit amet mauris pharetra posuere vel eu libero. Donec mattis, erat eu cursus volutpat, dui quam facilisis ante, eu dictum nulla justo in leo. Aliquam erat volutpat. Ut vel mi tellus. Praesent ut tempor nulla. Curabitur dignissim volutpat orci, sit amet porttitor velit blandit sodales.
</p><p>Donec augue libero, convallis eu consectetur vitae, congue vel diam. Duis odio nulla, venenatis sed sollicitudin ut, venenatis in massa. Suspendisse iaculis nisl sed mi semper in vulputate metus rhoncus. Aenean pharetra pellentesque consectetur. Aliquam pulvinar justo vitae arcu pretium facilisis. Duis neque ante, mattis a euismod vel, consectetur et nibh. Nam non nisl in mauris rutrum congue vehicula eget erat. Suspendisse malesuada orci id quam porta ac interdum est consectetur. Vestibulum placerat mollis ultrices. Sed ac turpis id diam blandit fermentum vel a magna.
</p><p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut ac quam nibh, vel porttitor odio. Fusce elit nibh, interdum eget egestas nec, tempor at justo. Quisque in diam a orci dictum semper. Mauris nibh leo, malesuada ac tristique ut, consequat ac ligula. Quisque quis velit justo, vitae vulputate arcu. Vivamus mattis porta sem, id tincidunt libero bibendum ac. Pellentesque ac ornare neque. Sed congue posuere neque, ut dignissim diam interdum at. Curabitur eu velit et nulla mattis tincidunt vehicula vitae turpis. Suspendisse rutrum turpis et diam dignissim sed porta elit gravida. Nulla dignissim luctus diam, sed hendrerit metus pulvinar vel. Proin ultricies imperdiet enim vel laoreet. Morbi iaculis tristique nibh, vitae dapibus turpis ullamcorper quis.
</p><p>Praesent porttitor ultricies mollis. Donec iaculis lacinia dui at convallis. Praesent dictum elementum dolor fringilla posuere. Aliquam euismod feugiat diam, vitae consectetur lacus ultricies et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas in est risus. Ut mollis nisl in magna lacinia ultrices at at enim. Sed quis nunc non elit aliquam dignissim. Suspendisse cursus massa et nunc scelerisque consequat. Praesent quam mi, mattis sed gravida quis, hendrerit ut lorem. Ut tortor leo, vestibulum sed placerat non, auctor eget ligula. In nec nunc at est bibendum vestibulum. In nibh lorem, auctor in accumsan at, scelerisque congue magna. Ut ullamcorper mi non libero fermentum placerat. Aliquam in tincidunt metus. Mauris justo orci, cursus id lobortis in, pellentesque eu metus. Nulla facilisi. Etiam convallis malesuada massa, vel euismod tellus cursus eget. Vivamus fermentum cursus metus eget iaculis.
</p>

<h2>In vino veritas</h2>
<h3>Etiam nuncdat</h3>

<p>Sed sagittis malesuada ornare. Sed eu mi nulla, a vehicula arcu. Vivamus egestas tellus quis ligula interdum sed dignissim nibh blandit. Quisque placerat justo sed nunc porttitor et facilisis ipsum volutpat. Nunc molestie vestibulum congue. Proin luctus magna eget libero fermentum vulputate porta nulla scelerisque. In sit amet quam turpis. Cras lectus elit, rutrum nec sollicitudin quis, tempor eu ipsum. Curabitur lacus ipsum, accumsan vitae pulvinar ac, ultricies ut neque. Morbi sapien metus, pharetra id tristique nec, tincidunt ut odio. In non lacinia nisl.
</p><p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ac leo eget risus cursus eleifend vitae pretium felis. Nunc vitae leo lorem. Curabitur congue, quam non convallis imperdiet, lectus mi aliquam tortor, commodo tincidunt ligula elit sit amet risus. Nullam accumsan, nunc in lacinia accumsan, ante mi vulputate lectus, ac cursus ligula odio ut metus. Sed in odio quam. Quisque id turpis velit, id lobortis arcu. Sed ante erat, lobortis ornare suscipit sed, tincidunt sit amet nisi. Etiam vel felis dui. Curabitur aliquam aliquam bibendum. Vivamus dapibus risus ut urna consectetur suscipit. Duis sit amet cursus urna. Morbi aliquam consequat mauris quis viverra. Etiam ut lacus sed risus varius commodo. Phasellus vel sem a eros facilisis accumsan. Sed euismod sollicitudin ornare.
</p><p>Donec eleifend, turpis nec pharetra hendrerit, nibh mi pretium est, vitae semper neque felis a felis. Aenean adipiscing mauris risus, eu aliquam libero. In consequat consequat justo, vitae aliquam nisl viverra eu. Vestibulum volutpat neque sed libero venenatis blandit. Cras nec felis mattis elit pretium posuere eget ac nisl. Nunc vel est urna, sit amet adipiscing massa. Sed at sollicitudin est. Suspendisse magna orci, dapibus eget vestibulum vel, venenatis eget lectus. Donec et quam purus. Phasellus elit leo, lacinia nec dictum vulputate, dictum vitae diam. Proin aliquet nisl molestie nunc aliquam nec ornare odio dictum. Duis ut fringilla magna. Nullam convallis elit sit amet magna viverra vel ultrices tellus hendrerit. Mauris rhoncus consequat nulla, et ultricies purus convallis at.
</p>

<h3>Muniplisset consectutor.</h3>
<p>Nullam facilisis, felis sed dapibus tincidunt, sem lorem adipiscing augue, sit amet sagittis orci turpis sit amet tellus. Donec porttitor metus vitae nunc ultrices tristique. Ut sit amet nulla in urna semper feugiat et vel nisl. Fusce vitae velit nec ipsum pulvinar lacinia in vel lacus. Cras sed nulla vitae elit ullamcorper gravida facilisis et neque. Sed fermentum, est luctus posuere sodales, ante augue egestas turpis, ac auctor tellus sem lobortis nunc. Etiam massa ante, ornare quis commodo ac, scelerisque quis augue. Nullam ac urna nunc, et faucibus nulla. Ut semper laoreet leo, in sollicitudin purus vulputate cursus. Nunc cursus lacus nibh, interdum convallis lorem. Sed viverra tincidunt lorem eget porttitor. Sed quis risus risus. Maecenas accumsan rutrum nulla, et interdum risus lobortis a. Curabitur bibendum scelerisque enim, sit amet porttitor justo dapibus sit amet. Vestibulum condimentum consectetur turpis, in volutpat quam euismod a. Maecenas non tellus ut nisi gravida bibendum.
</p><p>Fusce sem felis, sollicitudin a vulputate vitae, ultrices vel dolor. Mauris porta justo sit amet nulla fringilla dictum. Integer eget sem at lacus hendrerit venenatis. Donec vitae urna nulla, quis rutrum est. Vivamus gravida, nisi porta convallis malesuada, purus sem euismod elit, viverra vehicula tortor velit sit amet nibh. Vivamus lacinia rhoncus lacus vitae facilisis. Phasellus consequat dignissim erat, at commodo nibh convallis sit amet. Vivamus vestibulum risus et dolor iaculis id egestas mi aliquam. Proin lacinia justo vitae neque scelerisque eu faucibus eros interdum. Maecenas rhoncus ullamcorper sagittis. Suspendisse odio urna, viverra quis congue dictum, pellentesque vitae purus. In ac nisi at ligula tincidunt sollicitudin in at ante.
</p><p>Ut consectetur lorem vitae orci commodo blandit. Morbi risus eros, auctor in consectetur sed, ultrices at nisi. Vestibulum auctor commodo urna ac vulputate. Phasellus vestibulum diam ut libero malesuada semper. Nullam quam est, mattis ac semper vitae, hendrerit non orci. Aliquam justo neque, gravida ac aliquet in, ullamcorper a velit. Sed est erat, vestibulum sed posuere varius, interdum eget augue. Donec vitae urna neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi quis libero risus.
</p><p>Sed rutrum gravida mi non interdum. Ut eu mauris a lectus luctus malesuada porta vestibulum mi. Pellentesque eu arcu diam, quis rutrum diam. In turpis lectus, blandit sed mollis sit amet, pulvinar nec lorem. Sed blandit hendrerit euismod. Integer sollicitudin bibendum risus, ac porta elit accumsan vitae. Maecenas non consectetur lectus. Suspendisse vitae tempor eros. Mauris condimentum imperdiet ullamcorper. Donec lorem sapien, egestas a egestas ac, ullamcorper vitae risus. Aliquam erat volutpat. Aliquam scelerisque porttitor nunc, non ultrices elit varius in. Sed quis viverra nunc. Vivamus luctus adipiscing lorem eu dictum. Cras eros dui, molestie in iaculis vulputate, vestibulum non nisl. Morbi sodales scelerisque lacus pretium scelerisque. Ut consectetur orci id odio semper quis facilisis velit bibendum. Phasellus turpis orci, porttitor blandit interdum et, imperdiet ac enim. Nullam purus mi, adipiscing nec tincidunt a, iaculis sit amet elit. Aliquam erat volutpat.
</p><p>Aenean a lobortis ipsum. Pellentesque consectetur massa sit amet arcu sollicitudin id tincidunt lectus rhoncus. Morbi ut tortor purus, eu ornare lorem. Proin elementum mi at ante tincidunt commodo. In ac libero vitae neque dapibus pellentesque a nec risus. Fusce sed arcu ut erat commodo porttitor. Phasellus ut lorem sed erat accumsan suscipit vel facilisis magna. Nunc cursus, purus eu dictum ullamcorper, erat lectus tempus sem, id porta diam neque tempus ligula. Sed ac erat sit amet massa facilisis feugiat. Nunc tortor orci, pellentesque a sodales a, pharetra id nibh. Donec hendrerit odio at orci ornare bibendum. Sed rhoncus elit turpis. Pellentesque feugiat sem in risus sodales tempor. Mauris ut ante nec eros facilisis consequat vitae sed erat. Proin eu diam nulla. Sed vehicula turpis ut diam bibendum faucibus gravida ut lectus. Nullam semper magna sit amet tortor consequat porta. Nullam ante sapien, euismod eget posuere at, placerat non nulla. Nunc rhoncus, nibh vel convallis ornare, lectus lacus accumsan nunc, tempor luctus nunc quam at ipsum. Praesent id eros dui.
</p><p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sodales pretium dolor, sit amet condimentum odio tempus ac. Nulla vitae mattis dolor. Vestibulum eget leo at nibh fermentum tristique a a quam. In hac habitasse platea dictumst. In ornare augue eget risus scelerisque ultricies. Aenean sed aliquam justo. Nullam viverra imperdiet congue. Nulla eget molestie nunc. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vel massa eget nunc hendrerit ultricies. Curabitur nec lacus sed dolor sollicitudin semper eget quis mauris. Praesent eros felis, vulputate vitae ornare eu, bibendum eget mi. Vestibulum iaculis ligula ac lectus accumsan tristique.
</p>
</xsl:template>

<xsl:template mode="path" match="vars:meta">
	<xsl:text> &#x2192; Meine Noten</xsl:text>
</xsl:template>

</xsl:transform>
