<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
	xmlns:fo="http://www.w3.org/1999/XSL/Format" 
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xhtml="http://www.w3.org/1999/xhtml">
	<xsl:output method="xml" version="1.0" indent="yes" encoding="UTF-8"/>

	<xsl:template match="/">
		<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
			<!-- document infomation for PDF -->
			<!--axf:document-info name="subject" value="{/doc/head/subtitle}"/-->
			<fo:layout-master-set>
				<!-- DIN A4 (ISO 216) -->
			    <fo:simple-page-master master-name="default"
			        page-width="21cm"
			        page-height="29.7cm">
			        <fo:region-body margin="2.5cm" />
			    </fo:simple-page-master>
			    <!-- Timetable as DIN A4 -->
			    <fo:simple-page-master master-name="timetable"
			        page-width="29.7cm"
			        page-height="21cm">
			        <fo:region-body margin="2.5cm" />
			    </fo:simple-page-master>
			</fo:layout-master-set>
			
			<fo:page-sequence master-reference="default">
				<fo:flow flow-name="xsl-region-body">
				
					<xsl:apply-templates select="xhtml:html/xhtml:body/xhtml:*" />
					<!--<xsl:apply-templates select="//xhtml:div[@class=timetable]" />-->
					
					<fo:block font-family="Helvetica" font-size="8pt" text-align="right">
						Boldly generated by project Scetris, kindly supported by Apache FOP.
					</fo:block>
				</fo:flow>
			</fo:page-sequence> 
		</fo:root>	
	</xsl:template>

	<xsl:template match="xhtml:h1">
	    <fo:block font-family="Helvetica" font-size="30pt" font-weight="bold"> 
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:h2">
	    <fo:block font-family="Helvetica" font-size="24pt" font-weight="bold"> 
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:h3">
	    <fo:block font-family="Helvetica" font-size="18pt" font-weight="bold">
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:h4">
	    <fo:block font-family="Helvetica" font-size="16pt" font-weight="bold">
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:h5">
	    <fo:block font-family="Helvetica" font-size="14pt" font-weight="bold"> 
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:h6">
	    <fo:block font-family="Helvetica" font-size="12pt" font-weight="bold"> 
	        <xsl:value-of select="." />
	    </fo:block>
	</xsl:template>

	<xsl:template match="xhtml:p">
		<fo:block font-family="Helvetica" font-size="12pt" text-align="justify">
			<xsl:value-of select="." />
		</fo:block>
	</xsl:template>

	<!--<xsl:template match="xhtml:div">
		<fo:block font-family="Helvetica" font-size="12pt" text-align="justify">
			Timetable
			<xsl:value-of select="." />
		</fo:block>
	</xsl:template>-->

	<xsl:template match="@*|text()" />

</xsl:stylesheet>
