/* OutputConverter.java / 10:10:33 AM
 * Part of SCORE myCourses
 * 
 * Team Scetris: David Bialik, Julian Fleischer,
 * Hagen Mahnke, Konrad Reiche, André Zoufahl
 */

package de.fu.weave;

import javax.xml.transform.Source;
import javax.xml.transform.TransformerException;
import javax.xml.transform.stream.StreamResult;

/**
 * A pluggable Output-Module for the Weave-controllers.
 * 
 * Weave-controllers can generate output of various types. Native types are "xml" (raw output),
 * "xhtml", "xml" and "xsl" (xml and xsl are basically the same thing, but xsl includes a
 * stylesheet-PI; as are xhtml and html, but html is not valid XHTML for backwards compatibility).
 * Using a custom output-module a weave-controller may be enhanced with further output-modules.
 * 
 * @author Julian Fleischer
 * @since Iteration4
 */
public interface OutputConverter {
	/**
	 * 
	 * @param source
	 * @param result
	 *            By convention the StreamResult <b>must</b> have an InputStream set.
	 * @throws TransformerException
	 * @throws UnsupportedResultTypeException
	 * @throws IllegalArgumentException
	 *             If the StreamResult does not have an InputStream set.
	 * @since Iteration4
	 */
	void convert(Source source, StreamResult result) throws TransformerException,
			UnsupportedResultTypeException;

	/**
	 * Gets the character encoding that the output is converted to.
	 * 
	 * @return null if no Character-Encoding-Information should be sent. The charset as a String
	 *         otherwise (e.g. UTF-8).
	 * @since Iteration4
	 */
	String getCharacterEncoding();

	/**
	 * 
	 * @return
	 * @since Iteration4
	 */
	String getMimeType();

	/**
	 * Check whether the Controller should transform the source-document using the currently
	 * executed actions native template prior to applying the output-conversion.
	 * 
	 * If this returns false, the Controller will pass raw XML-date to the converter, otherwise it
	 * will pass the already preprocessed data which has been generated by applying the actions
	 * template before. In other words: If this method returns false, you will receive raw xml data,
	 * otherwise XHTML which has been obtained by applying the template which is annotated via
	 * {@see de.fu.weave.annotation.Action}.
	 * 
	 * @return
	 * @since Iteration4
	 */
	boolean isAppliedAfterNativeTemplate();
}
